import Config from "react-native-config";

export default {
  NODE_ENV: Config.NODE_ENV,
  DEV_BASE_URL: Config.DEV_BASE_URL,
  PROD_BASE_URL: Config.PROD_BASE_URL,
  GOOGLE_LOGIN_CLIENT_ID: Config.GOOGLE_LOGIN_CLIENT_ID,
  GOOGLE_CLIENT_IOS_CLIENT_ID: Config.GOOGLE_CLIENT_IOS_CLIENT_ID,
  CLOUDINARY_CLOUD_NAME: Config.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: Config.CLOUDINARY_API_KEY,
  CLOUDINARY_UPLOAD_PRESET: Config.CLOUDINARY_UPLOAD_PRESET,
};
