export const PREPEND_FEED_POST = "PREPEND_FEED_POST";
export const APPEND_FEED_POST = "APPEND_FEED_POST";
export const SET_FEED_POSTS = "SET_FEED_POSTS";
export const REMOVE_FEED_POST = "REMOVE_FEED_POST";
export const CLEAR_FEED_POSTS = "CLEAR_FEED_POSTS";

export const PREPEND_USER_POST = "PREPEND_USER_POST";
export const APPEND_USER_POST = "APPEND_USER_POST";
export const SET_USERS_POSTS = "SET_USERS_POSTS";
export const REMOVE_USER_POST = "REMOVE_USER_POST";
export const CLEAR_USERS_POSTS = "CLEAR_USERS_POSTS";
