// Feed Action Types
export const SET_COMMENT = 'SET_COMMENT';
export const SET_COMMENTS = "SET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_AT_INDEX = "ADD_COMMENT_AT_INDEX";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const SET_LOADING = "SET_LOADING";
export const SET_REFRESHING = "SET_REFRESHING";
export const SET_MODE = "SET_MODE";
export const ADD_TO_SELECTED_COMMENTS = "ADD_TO_SELECTED_COMMENTS";
export const REMOVE_FROM_SELECTED_COMMENTS = "REMOVE_FROM_SELECTED_COMMENTS";
export const SET_SELECTED_COMMENTS = "SET_SELECTED_COMMENTS";
export const OVERLAY_PRESS = "OVERLAY_PRESS";
export const ON_DELETE_PRESS = "ON_DELETE_PRESS";
