// Feed Action Types
export const SET_STORIES = "SET_STORIES";
export const SET_PROFILE_STORIES = "SET_PROFILE_STORIES";
export const ADD_PROFILE_STORIES = "ADD_PROFILE_STORIES";
export const REMOVE_PROFILE_STORIES = "REMOVE_PROFILE_STORIES";
export const MARK_STORY_AS_VIEWED = "MARK_STORY_AS_VIEWED";
export const MARK_PROFILE_STORY_AS_VIEWED = "MARK_PROFILE_STORY_AS_VIEWED";
