// Theme Action Types

export const SET_PROFILE_POSTS = 'SET_PROFILE_POSTS';
export const UPDATE_LOCAL_URI = 'UPDATE_LOCAL_URI';
export const ADD_PROFILE_POST = 'ADD_PROFILE_POST';
export const DELETE_PROFILE_POST = 'DELETE_PROFILE_POST';
export const SET_FOLLOWERS_COUNT = 'SET_FOLLOWERS_COUNT';
export const SET_FOLLOWING_COUNT = 'SET_FOLLOWING_COUNT';
export const LIKE_A_POST = "LIKE_A_POST"
export const UNLIKE_A_POST = "UNLIKE_A_POST"
export const UPDATE_POST_LIKE_COUNT = 'UPDATE_POST_LIKE_COUNT';
export const UPDATE_POST_COMMENT_COUNT = 'UPDATE_POST_COMMENT_COUNT';
export const LOGOUT = 'LOGOUT';